[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "light"

# Primary accent color for interactive elements.
primaryColor = "#F2677F"

# Background color for the main content area.
backgroundColor = "#ffffff"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#fafafa"

# Color used for almost all text.
textColor = "#161f29"

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
font = "sans-serif"